name: Emmanuel Kadiebwe
description: Étudiant Master Ingénieur Administration Systèmes, Réseaux & Cybersécurité — en recherche de stage (support IT, admin sys/réseau, cybersécurité)
avatar: /images/avatar.jpg
 
footer-links:
  email: emmanuel@kadiebwe.eu
  github: Hendrix44
  linkedin: emmanuel-kadiebwe
 
url: https://hendrix44.github.io
baseurl: ""
 
permalink: /:title/
 
markdown: kramdown
exclude: ["README.md", "LICENSE"]
plugins:
  - jekyll-sitemap
  - jekyll-feed
 
